import 'package:equatable/equatable.dart';
import 'package:on_time_front/core/database/database.dart';

class ScheduleWithPlace extends Equatable {
  const ScheduleWithPlace({required this.schedule, required this.place});

  // The classes are generated by drift for each of the tables involved in the
  // join.
  final Schedule schedule;
  final Place place;

  @override
  List<Object?> get props => [schedule, place];

  @override
  String toString() {
    return 'ScheduleWithPlace{schedule: $schedule, place: $place}';
  }
}
