import '../entities/schedule_entity.dart';
import '../entities/time_correction_conflict.dart';
import '../entities/schedule_time_correction.dart';
import '../entities/schedule_time_resolution.dart';
import 'recurrence_engine.dart';
import 'recurrence_rule.dart';

final class TimeCorrectionExclusion {
  const TimeCorrectionExclusion(this.segmentId, this.slot, this.ordinal);
  final String segmentId;
  final String slot;
  final int ordinal;
}

final class TimeCorrectionRowMapping {
  const TimeCorrectionRowMapping(this.original, this.slot);
  final ScheduleEntity original;

  /// Null means explicit standalone preservation, never deletion.
  final RecurrenceSlot? slot;
  bool get detached => slot == null;
}

final class TimeCorrectionExclusionMapping {
  const TimeCorrectionExclusionMapping(this.original, this.slot);
  final TimeCorrectionExclusion original;

  /// The original tombstone survives whether or not a new slot corresponds.
  final RecurrenceSlot? slot;
}

final class RecurringTimeCorrectionMapping {
  RecurringTimeCorrectionMapping({
    required this.rule,
    required this.automaticallyRetainedCount,
    required List<TimeCorrectionRowMapping> rows,
    required List<ScheduleEntity> protectedRows,
    required List<TimeCorrectionExclusionMapping> exclusions,
    required List<RecurrenceSlot> protectedSlots,
    required this.workUnits,
    required this.firstSlot,
    List<RecurrenceSlot> conflictExclusions = const [],
  }) : rows = List.unmodifiable(rows),
       protectedRows = List.unmodifiable(protectedRows),
       exclusions = List.unmodifiable(exclusions),
       protectedSlots = List.unmodifiable(protectedSlots),
       conflictExclusions = List.unmodifiable(conflictExclusions);

  final RecurrenceRule rule;
  final bool automaticallyRetainedCount;
  final List<TimeCorrectionRowMapping> rows;
  final List<ScheduleEntity> protectedRows;
  final List<TimeCorrectionExclusionMapping> exclusions;
  final List<RecurrenceSlot> protectedSlots;
  final int workUnits;
  final RecurrenceSlot? firstSlot;
  final List<RecurrenceSlot> conflictExclusions;
}

final class RecurringTimeCorrectionCountRequired implements Exception {
  const RecurringTimeCorrectionCountRequired();
}

final class RecurringTimeCorrectionRequest {
  RecurringTimeCorrectionRequest({
    required this.anchorReview,
    required this.rule,
    required this.endExplicitlyChosen,
    Set<String> excludedConflictSlots = const {},
  }) : excludedConflictSlots = Set.unmodifiable(excludedConflictSlots);
  final ScheduleTimeCorrectionReview anchorReview;
  final RecurrenceRule rule;
  final bool endExplicitlyChosen;
  final Set<String> excludedConflictSlots;
}

final class RecurringTimeCorrectionReview {
  RecurringTimeCorrectionReview({
    required this.request,
    required this.mapping,
    required this.sourceDigest,
    this.conflictProof,
    required Map<String, ScheduleTimeResolutionStatus> unresolvedOverrides,
  }) : unresolvedOverrides = Map.unmodifiable(unresolvedOverrides);
  final RecurringTimeCorrectionRequest request;
  final RecurringTimeCorrectionMapping mapping;
  final String sourceDigest;
  final TimeCorrectionConflictProof? conflictProof;

  /// Stable IDs needing their own explicit occurrence selection before commit.
  final Map<String, ScheduleTimeResolutionStatus> unresolvedOverrides;
}

final class RecurringTimeCorrectionCommand {
  RecurringTimeCorrectionCommand({
    required this.review,
    required this.mutationId,
    required Set<String> confirmedDetachedIds,
    required Set<String> confirmedUnmatchedExclusions,
    Set<String> acknowledgedUncertainIds = const {},
  }) : acknowledgedUncertainIds = Set.unmodifiable(acknowledgedUncertainIds),
       confirmedDetachedIds = Set.unmodifiable(confirmedDetachedIds),
       confirmedUnmatchedExclusions = Set.unmodifiable(
         confirmedUnmatchedExclusions,
       );
  final RecurringTimeCorrectionReview review;
  final String mutationId;
  final Set<String> confirmedDetachedIds;
  final Set<String> acknowledgedUncertainIds;

  /// Exact source segment ID and civil slot, generated by the review service.
  final Set<String> confirmedUnmatchedExclusions;
}
