part of 'theme.dart';

ColorScheme _colorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: AppColors.blue,
  onPrimary: AppColors.white,
  primaryContainer: AppColors.blue.shade200,
  onPrimaryContainer: AppColors.blue.shade900,
  secondary: AppColors.green,
  onSecondary: AppColors.white,
  secondaryContainer: AppColors.green.shade100,
  onSecondaryContainer: AppColors.green.shade900,
  tertiary: AppColors.yellow,
  onTertiary: AppColors.white,
  tertiaryContainer: AppColors.yellow.shade100,
  onTertiaryContainer: AppColors.yellow.shade900,
  error: AppColors.red,
  onError: Colors.white,
  errorContainer: AppColors.red.shade50,
  onErrorContainer: AppColors.red.shade900,
  surfaceDim: AppColors.grey.shade400,
  surface: AppColors.white,
  surfaceBright: AppColors.white,
  surfaceContainerLowest: AppColors.grey.shade50,
  surfaceContainerLow: AppColors.grey.shade100,
  surfaceContainer: AppColors.grey.shade200,
  surfaceContainerHigh: AppColors.grey.shade300,
  surfaceContainerHighest: AppColors.grey.shade400,
  onSurface: AppColors.grey[950]!,
  onSurfaceVariant: AppColors.grey.shade400,
  outlineVariant: AppColors.grey.shade400,
  outline: AppColors.grey.shade600,
);
